エラーが出るようになったので追記
NoMethodError: undefined method `last_comment' for
#<Rake::Application:0x007fc626ae96f8>
/Users/yagyumasahiro/chatspace/chat-space/Rakefile:6:in `<top
(required)>'
/Users/yagyumasahiro/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/yagyumasahiro/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'